version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: makeitshort_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Database=${POSTGRES_DB};Username=${DB_USER};Password=${DB_PASSWORD}
      - Shortener__BaseUrl=${Shortener__BaseUrl}
      - DOTNET_URLS=http://0.0.0.0:8080
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    container_name: makeitshort_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: